### ISSUE TITLE
Compiling for OSX using gfortran.

### ISSUE THREAD

**Issue by hrwinterbottom** [JCSDA/py-ncepbufr#7]
The most recent gcc gfortran compiler (currently, version 7) coding standard does not permit the conversion of character strings to integer values. This issue comes up into play within subroutine src/ifxy.f, line 63. Rolling back and using gcc gfortran version 6.1.0 does the trick.

To install, using homebrew, do:

    brew install -s caskroom/cask/gfortran

Building using this compiler should resolved BUFR I/O issues.

**Comment by jswhit** [comment]
@srherbener found the following workaround:

"Hi Jeff,

I found the problem. It's actually pretty easy to deal with which is fortunate.

I am using anaconda for my python installation, and anaconda provides a libgfortran.dylib (code for the Fortran intrinsics). Not only that, distutils (setup.py) puts the anaconda libgfortran in the link path and not the libgfortran that comes with whatever gfortran compiler you install on your system. The anaconda libgfortran is apparently compatible with gfortran 6, and not compatible with gfortran 7 (the read command is one of the Fortran intrinsics).

The way to fix this is to download gcc into the anaconda space:

  conda install -c anaconda gcc

After doing the above install, anaconda will contain gcc and gfortran (that matches up with the anaconda libgfortran).

While I was debugging, I was found a workaround where I set FC, F77, F90, CC to the corresponding compilers in my gcc7 installation, and overrode the loader command by also setting LDFLAGS in my environment. (for the iMac, LDFLAGS="-bundle -undefined dynamic_lookup -Lpath_to_my_gcc7_lib". The LDFLAGS setting put the path to the installed libgfortran ahead of the anaconda path which fixed the issue.

This workaround isn't quite as good as the fix I mention above, but it does allow flexibility for the user to experiment with new compilers. Because of this, I made a couple small changes to makebufr.sh so that the FC and CC environment settings are picked up and used in that scripts (instead of being forced to "gfortran" and "cc"). I've created a pull request with this change.

Hope this helps for the other person with the read command failure.

Steve"
